[{oxstyle include=$oViewConf->getModuleUrl('enderecoams203','out/src/css/EnderecoJSClient.css')  }]
[{if $oView->insertBootstrapCSS()}]
    [{oxstyle include=$oViewConf->getModuleUrl('enderecoams203','out/src/css/bootstrap.modal.css')  }]
[{/if}]

[{assign var="enderecoAMSTheme" value=$oView->getTheme()}]
[{if $enderecoAMSTheme == 0}]
    [{oxstyle include=$oViewConf->getModuleUrl('enderecoams203','out/src/css/azure.css')  }]
[{elseif $enderecoAMSTheme == 1}]
    [{oxstyle include=$oViewConf->getModuleUrl('enderecoams203','out/src/css/roxid.css')  }]
[{elseif $enderecoAMSTheme == 2}]
    [{oxstyle include=$oViewConf->getModuleUrl('enderecoams203','out/src/css/roxive.css')  }]
[{elseif $enderecoAMSTheme == 3}]
    [{oxstyle include=$oViewConf->getModuleUrl('enderecoams203','out/src/css/custom.css')  }]
[{/if}]
